---
config:
  webserver:
    expose_config: "True"
  logging:
    remote_logging: "True"
    remote_base_log_folder: "cloudwatch://arn:aws:logs:eu-north-1:381492273274:log-group:/showcase/prod/airflow/service"
    remote_log_conn_id: "" # Use IAM role policy attached to the pod

postgresql:
  enabled: false

pgbouncer:
  enabled: true

statsd:
  enabled: false

redis:
  enabled: false

webserver:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::381492273274:role/ShowcaseAirflow"

  # Bump up all probe times, especially initial delay, as Fargate pods take a while to start up and cycle.
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 60
    failureThreshold: 5
    periodSeconds: 30
    scheme: HTTP

  readinessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 60
    failureThreshold: 5
    periodSeconds: 30
    scheme: HTTP

  # Wait for at most 5 minutes (6*30s) for the webserver container to startup.
  # livenessProbe kicks in after the first successful startupProbe
  startupProbe:
    timeoutSeconds: 20
    failureThreshold: 6
    periodSeconds: 30
    scheme: HTTP

  resources:
    limits:
      cpu: "0.75"
      memory: "1.75Gi"
    requests:
      cpu: "0.75"
      memory: "1.75Gi"

triggerer:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::381492273274:role/ShowcaseAirflow"

dagProcessor:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::381492273274:role/ShowcaseAirflow"

cleanup:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::381492273274:role/ShowcaseAirflow"

migrateDatabaseJob:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::381492273274:role/ShowcaseAirflow"

scheduler:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::381492273274:role/ShowcaseAirflow"

  resources:
    limits:
      cpu: "0.5"
      memory: "1.5Gi"
    requests:
      cpu: "0.5"
      memory: "1.5Gi"

logs:
  persistence:
    enabled: false

workers:
  persistence:
    enabled: false

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::381492273274:role/ShowcaseAirflow"

  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 20
    failureThreshold: 6
  resources:
    limits:
      cpu: "1"
      memory: "3.5Gi"
    requests:
      cpu: "1"
      memory: "3.5Gi"

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: git@github.com:cloudership/showcase_airflow_dags.git
    branch: master
    subPath: ""
    sshKeySecret: airflow-gitsync
    knownHosts: |-
      github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl

    resources:
      limits:
        cpu: "0.25"
        memory: "1Gi"
      requests:
        cpu: "0.25"
        memory: "1Gi"
